### PR TITLE
Support definition files.

### LINKED ISSUE #15: Default config does not pick up `.d.ts` files
Just what it says on the tin. We tried to add a definition file, it failed to compile; we changed the extension to just `.ts` instead of `.d.ts` and it worked.

Probably just what the tree is configured to snag, I'm guessing. Will take a look down the line.

### PR DESCRIPTION
**Pull request by chriskrycho**
Fixes #15.

### CODE REVIEW

**Comment by chriskrycho** [comment]
N.b. this needs more testing. I'm getting all sorts of weird errors, and I'm not sure whether they're related to this or not.

**Comment by locks** [comment]
Talk to me, Chis.

**Comment by chriskrycho** [comment]
I'm going to test this later; I suspect – though I do not yet have any proof – that fixing the tsconfig may have resolved this.

**Comment by chriskrycho** [comment]
NOPE. Resolved by #22.

**Pull request closed without merging**
