### PR TITLE
Further clarification of ember install effects

### PR DESCRIPTION
**Pull request by dustinfarris**
/cc @chriskrycho please review

### CODE REVIEW

**Comment by dustinfarris** [comment]
Will probably need to include a note for addon authors as well since ember puts these in devDependencies which probably won't work for addons.

**Comment by winding-lines** [comment]
Dustin, are you testing your changes in a typescript application? 

Marius
---

**Comment by dustinfarris** [comment]
@winding-lines yes I installed successfully using `ember install`, however note that deps are added to `devDependencies` not `dependencies` which I believe still needs to be clarified for addon authors.

**Comment by dustinfarris** [comment]
@winding-lines to be clear i only tested that the install process had the same effect

- same packages installed
- package.json updated
- typescript runs during build without errors

I have not tested that my addon works with ember-cli-typescript in general.  I am doing that now.

**Pull request merged**
